export const funFacts = [
  "The longest river in the world is the Nile, stretching about 4,135 miles.",
  "The chemical symbol for gold is Au, from the Latin word 'aurum.'",
  "Australia is both a country and a continent.",
  "The human body has 206 bones in adulthood.",
  "The Great Barrier Reef is the largest coral reef system on Earth.",
  "Shakespeare wrote 37 plays that are widely accepted as authentic.",
  "The capital of Canada is Ottawa, not Toronto or Montreal.",
  "Light travels at approximately 186,282 miles per second.",
  "Mount Kilimanjaro is the tallest mountain in Africa.",
  "The currency of Japan is the yen.",
  "Water boils at 100 degrees Celsius at sea level.",
  "The Statue of Liberty was a gift from France to the United States.",
  "Saturn is famous for its prominent ring system.",
  "The Mona Lisa was painted by Leonardo da Vinci.",
  "The Olympic Games originated in ancient Greece.",
  "The hardest natural substance on Earth is diamond.",
  "Mercury is the closest planet to the Sun.",
  "The human heart has four chambers.",
  "The Amazon rainforest produces roughly 20% of the world’s oxygen.",
  "The first Super Bowl was played in 1967.",
  "The capital of Spain is Madrid.",
  "The tallest animal in the world is the giraffe.",
  "The piano has 88 keys.",
  "The movie Titanic was directed by James Cameron.",
  "The smallest U.S. state by area is Rhode Island.",
  "A group of crows is called a murder.",
  "The speed of sound is about 343 meters per second at sea level.",
  "Thomas Edison held over 1,000 U.S. patents.",
  "The largest ocean on Earth is the Pacific Ocean.",
  "Bats are the only mammals capable of true flight.",
  "The square root of 144 is 12.",
  "The longest-running Broadway show is The Phantom of the Opera.",
  "Venus rotates in the opposite direction of most planets.",
  "The national animal of China is the giant panda.",
  "The Titanic sank in 1912.",
  "There are 50 stars on the U.S. flag representing the states.",
  "The tallest building in the world is the Burj Khalifa.",
  "The human brain uses about 20% of the body’s energy.",
  "Soccer is known as football in most countries outside the U.S.",
  "The first man to walk on the Moon was Neil Armstrong.",
  "The largest desert in the world is Antarctica, technically a cold desert.",
  "The currency of the United Kingdom is the pound sterling.",
  "The longest bone in the human body is the femur.",
  "A leap year occurs every four years.",
  "The capital of Brazil is Brasília.",
  "Bees communicate through a dance known as the waggle dance.",
  "The Great Wall of China is over 13,000 miles long.",
  "The human eye can distinguish roughly 10 million colors.",
  "The first Harry Potter book was published in 1997.",
  "The chemical formula for table salt is NaCl.",
  "The Empire State Building has 102 floors.",
  "Polar bears have black skin beneath their white fur.",
  "The largest planet in our solar system is Jupiter.",
  "The official language of Brazil is Portuguese.",
  "The first iPhone was released in 2007.",
  "The Sahara Desert covers much of North Africa.",
  "The capital of South Korea is Seoul.",
  "Butterflies taste with their feet.",
  "The longest U.S. river is the Missouri River.",
  "The Nobel Prizes were established by Alfred Nobel’s will.",
  "The human body has five senses traditionally taught in school.",
  "Penguins cannot fly but are excellent swimmers.",
  "The White House has 132 rooms.",
  "The metric system is based on units of ten.",
  "The first Disney animated feature film was Snow White and the Seven Dwarfs.",
  "An octopus has three hearts.",
  "The tallest waterfall in the world is Angel Falls in Venezuela.",
  "The United Nations headquarters is located in New York City.",
  "A heptagon has seven sides.",
  "The first woman to win a Nobel Prize was Marie Curie.",
  "The capital of Egypt is Cairo.",
  "The world’s largest island is Greenland.",
  "Basketball was invented by James Naismith.",
  "The human body’s largest organ is the skin.",
  "The freezing point of water is 0 degrees Celsius.",
  "The currency of India is the rupee.",
  "The Leaning Tower of Pisa began leaning during construction.",
  "An adult human has 32 teeth including wisdom teeth.",
  "The largest mammal on Earth is the blue whale.",
  "The first Star Wars film was released in 1977.",
  "Lightning is hotter than the surface of the Sun.",
  "The capital of Turkey is Ankara.",
  "The chemical symbol for iron is Fe.",
  "A marathon race is 26.2 miles long.",
  "The first president of the United States was George Washington.",
  "The Andes is the longest continental mountain range.",
  "There are seven colors in a traditional rainbow.",
  "The largest lake by surface area is the Caspian Sea.",
  "Humans share about 98% of their DNA with chimpanzees.",
  "The first successful powered airplane flight was by the Wright brothers in 1903.",
  "The capital of Thailand is Bangkok.",
  "A group of lions is called a pride.",
  "The periodic table currently has 118 confirmed elements.",
  "The tallest statue in the world is the Statue of Unity in India.",
  "The Earth completes one rotation every 24 hours.",
  "The fastest land animal is the cheetah.",
  "The capital of Argentina is Buenos Aires.",
  "Chocolate comes from cacao beans.",
  "The longest English word in many dictionaries is pneumonoultramicroscopicsilicovolcanoconiosis.",
  "The capital of Switzerland is Bern.",
  "The chemical symbol for silver is Ag, from the Latin 'argentum.'",
  "The largest country by land area is Russia.",
  "Humans have five fingers on each hand, including the thumb.",
  "The first modern Olympic Games were held in Athens in 1896.",
  "Pluto was reclassified as a dwarf planet in 2006.",
  "The currency of Mexico is the peso.",
  "The Mississippi River flows into the Gulf of Mexico.",
  "The inventor of the telephone was Alexander Graham Bell.",
  "A triangle’s interior angles always add up to 180 degrees.",
  "The largest species of shark is the whale shark.",
  "The capital of Italy is Rome.",
  "Coffee beans are actually seeds of a fruit called a cherry.",
  "The movie Jurassic Park was released in 1993.",
  "The tallest grass in the world is bamboo.",
  "The chemical symbol for potassium is K.",
  "The first email was sent in 1971.",
  "The capital of New Zealand is Wellington.",
  "Sound cannot travel through a vacuum.",
  "The longest bone in the arm is the humerus.",
  "The currency of China is the yuan.",
  "The first man-made satellite was Sputnik 1, launched by the Soviet Union.",
  "The primary ingredient in glass is sand.",
  "The capital of Ireland is Dublin.",
  "The Atlantic Ocean separates the Americas from Europe and Africa.",
  "The fastest bird in a dive is the peregrine falcon.",
  "The world’s largest hot desert is the Sahara.",
  "The first video game console was the Magnavox Odyssey.",
  "The human body contains about five liters of blood.",
  "The Statue of Liberty stands on Liberty Island in New York Harbor.",
  "The chemical symbol for lead is Pb.",
  "The longest day of the year in the Northern Hemisphere occurs around June 21.",
  "The capital of Norway is Oslo.",
  "The largest internal organ in the human body is the liver.",
  "The currency of South Africa is the rand.",
  "The first U.S. state to ratify the Constitution was Delaware.",
  "Lightning strikes Earth about 100 times per second.",
  "The Eiffel Tower was completed in 1889.",
  "The planet Mars is often called the Red Planet due to iron oxide on its surface.",
  "The capital of Greece is Athens.",
  "There are 24 hours in a day.",
  "The world’s deepest ocean trench is the Mariana Trench.",
  "The longest-running animated TV show is The Simpsons.",
  "The chemical symbol for mercury is Hg.",
  "The largest freshwater lake by volume is Lake Baikal.",
  "The capital of Chile is Santiago.",
  "Cheetahs cannot roar but they can purr.",
  "The human nose can detect over a trillion different scents.",
  "The first successful vaccine was developed for smallpox.",
  "The currency of Sweden is the krona.",
  "The Great Lakes contain about 20% of the world’s fresh surface water.",
  "The largest volcano in the solar system is Olympus Mons on Mars.",
  "The capital of the Netherlands is Amsterdam.",
  "The average human body temperature is about 98.6 degrees Fahrenheit.",
  "The first woman to fly solo across the Atlantic was Amelia Earhart.",
  "The chemical symbol for copper is Cu.",
  "The shortest war in history lasted less than one hour between Britain and Zanzibar.",
  "The capital of Poland is Warsaw.",
  "A prism separates white light into a spectrum of colors.",
  "The first Academy Awards ceremony took place in 1929.",
  "The currency of Switzerland is the Swiss franc.",
  "The kangaroo is native to Australia.",
  "The longest railway in the world is the Trans-Siberian Railway.",
  "The capital of Finland is Helsinki.",
  "A baseball team fields nine players at a time.",
  "The first successful heart transplant was performed in 1967.",
  "The chemical symbol for zinc is Zn.",
  "The Mediterranean Sea connects to the Atlantic Ocean through the Strait of Gibraltar.",
  "The capital of Portugal is Lisbon.",
  "The largest bird by wingspan is the wandering albatross.",
  "The first commercial jet airliner was the de Havilland Comet.",
  "The currency of Egypt is the Egyptian pound.",
  "The human skeleton renews itself approximately every 10 years.",
  "The tallest active volcano in the world is Ojos del Salado.",
  "The capital of Hungary is Budapest.",
  "The first Earth Day was celebrated in 1970.",
  "The chemical symbol for sodium is Na.",
  "The Panama Canal connects the Atlantic and Pacific Oceans.",
  "The largest species of cat is the Siberian tiger.",
  "The currency of Canada is the Canadian dollar.",
  "The longest word with no repeated letters is 'uncopyrightable.'",
  "The capital of the Philippines is Manila.",
  "The human ear has three tiny bones called ossicles.",
  "The first successful personal computer was the Apple II.",
  "The Moon’s gravity is about one-sixth that of Earth.",
  "The chemical symbol for tin is Sn.",
  "The capital of Kenya is Nairobi.",
  "An acre equals 43,560 square feet.",
  "The world’s largest flower is the rafflesia.",
  "The currency of Brazil is the real.",
  "The first televised presidential debate in the U.S. was in 1960.",
  "The longest-running British monarch was Queen Elizabeth II.",
  "The capital of Vietnam is Hanoi.",
  "Honey never spoils when stored properly.",
  "The first country to grant women the right to vote nationally was New Zealand.",
  "The chemical symbol for platinum is Pt.",
  "The world’s largest peninsula is the Arabian Peninsula.",
  "The capital of Colombia is Bogotá.",
  "A standard deck of playing cards has 52 cards.",
  "The tallest species of penguin is the emperor penguin.",
  "The speed of Earth’s orbit around the Sun is about 67,000 miles per hour.",
  "The capital of Belgium is Brussels.",
  "The chemical symbol for helium is He.",
  "The largest country in South America by area is Brazil.",
  "An ostrich’s eye is larger than its brain.",
  "The first Winter Olympics were held in 1924 in Chamonix, France.",
  "The square has four equal sides and four right angles.",
  "The currency of Russia is the ruble.",
  "The longest bridge in the United States is the Lake Pontchartrain Causeway.",
  "The inventor of the light bulb is commonly credited to Thomas Edison.",
  "The human body has 12 pairs of ribs.",
  "The capital of Austria is Vienna.",
  "Ice floats on water because it is less dense than liquid water.",
  "The largest species of bear is the polar bear.",
  "The first Star Trek television series debuted in 1966.",
  "The chemical symbol for aluminum is Al.",
  "The capital of Denmark is Copenhagen.",
  "The human stomach contains acid strong enough to dissolve metal.",
  "The longest-running U.S. game show is The Price Is Right.",
  "The currency of Turkey is the lira.",
  "The Pacific Ring of Fire is known for frequent earthquakes and volcanoes.",
  "The capital of Peru is Lima.",
  "The first element on the periodic table is hydrogen.",
  "The world’s tallest tree species is the coast redwood.",
  "The first woman in space was Valentina Tereshkova.",
  "The chemical symbol for chlorine is Cl.",
  "The Great Pyramid of Giza is the oldest of the Seven Wonders of the Ancient World.",
  "The capital of Malaysia is Kuala Lumpur.",
  "A hexagon has six sides.",
  "The longest-serving U.S. president was Franklin D. Roosevelt.",
  "The currency of South Korea is the won.",
  "The average baseball game lasts about three hours.",
  "The largest moon of Saturn is Titan.",
  "The capital of Argentina province-level city is Buenos Aires.",
  "The first microwave oven was invented after radar technology experiments.",
  "The chemical symbol for carbon is C.",
  "A kilometer equals 1,000 meters.",
  "The Amazon River has more water flow than any other river.",
  "The capital of Pakistan is Islamabad.",
  "The human body has over 600 muscles.",
  "The first man-made object to reach space was the V-2 rocket.",
  "The currency of Israel is the shekel.",
  "The longest movie ever made exceeds 35 hours in length.",
  "The capital of Morocco is Rabat.",
  "An isosceles triangle has at least two equal sides.",
  "The largest organ inside the human body is the liver.",
  "The chemical symbol for nitrogen is N.",
  "The world’s highest capital city is La Paz, Bolivia.",
  "The first modern computer mouse was invented in the 1960s.",
  "The currency of Thailand is the baht.",
  "The capital of Indonesia is Jakarta.",
  "The Earth has one natural satellite, the Moon.",
  "The fastest fish in the ocean is the sailfish.",
  "The first paperback books became popular in the 1930s.",
  "The chemical symbol for calcium is Ca.",
  "The capital of Scotland is Edinburgh.",
  "The longest cave system in the world is Mammoth Cave in Kentucky.",
  "The human eye blinks about 15 to 20 times per minute.",
  "The currency of Argentina is the peso.",
  "The first artificial heart implant surgery occurred in 1982.",
  "The capital of Ukraine is Kyiv.",
  "A pentagon has five sides.",
  "The largest species of turtle is the leatherback sea turtle.",
  "The first smartphone is widely considered to be IBM’s Simon.",
  "The chemical symbol for magnesium is Mg.",
  "The capital of Cuba is Havana.",
  "The brain is about 60% fat by composition.",
  "The longest-running soap opera is Guiding Light.",
  "The currency of Norway is the krone.",
  "The first country to host the FIFA World Cup was Uruguay.",
  "The capital of Venezuela is Caracas.",
  "The human body produces about one liter of saliva per day.",
  "The largest species of eagle is the harpy eagle.",
  "The chemical symbol for sulfur is S.",
  "The tallest dam in the United States is Oroville Dam.",
  "The capital of Bangladesh is Dhaka.",
  "The first subway system opened in London in 1863.",
  "The currency of Singapore is the Singapore dollar.",
  "A right angle measures 90 degrees.",
  "The largest population city in Canada is Toronto.",
  "The first photograph was taken in the 1820s.",
  "The chemical symbol for phosphorus is P.",
  "The capital of Romania is Bucharest.",
  "The shortest month of the year is February.",
  "The first animated character to receive a Hollywood Walk of Fame star was Mickey Mouse.",
  "The currency of the Czech Republic is the koruna.",
  "The largest mammal on land is the African elephant.",
  "The capital of Sri Lanka’s legislative city is Sri Jayawardenepura Kotte.",
  "The human body has 23 pairs of chromosomes.",
  "The first successful cloning of a mammal produced Dolly the sheep.",
  "The chemical symbol for nickel is Ni.",
  "The capital of Ethiopia is Addis Ababa.",
  "The longest river in Europe is the Volga.",
  "The first widely used web browser was Mosaic.",
  "The currency of Indonesia is the rupiah.",
  "The speed limit on many U.S. highways is 65 miles per hour.",
  "The largest island nation in the world is Indonesia.",
  "The chemical symbol for cobalt is Co.",
  "The capital of Croatia is Zagreb.",
  "A dozen equals 12 items.",
  "The first Nobel Peace Prize was awarded in 1901.",
  "The currency of Poland is the złoty.",
  "The tallest mountain in North America is Denali.",
  "The human liver can regenerate damaged tissue.",
];
