import fs from "node:fs/promises";
import path from "node:path";

const repoRoot = process.cwd();
const guidesDir = path.join(repoRoot, "app", "strategy-guides", "guides");
const outFile = path.join(guidesDir, "index.ts");

function toPosixPath(p) {
  return p.split(path.sep).join("/");
}

async function fileExists(p) {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

function extractExportNames(sourceText) {
  // Match: export const name =
  const names = [];
  const re = /export\s+const\s+([A-Za-z_$][\w$]*)\s*=/g;
  for (let m; (m = re.exec(sourceText)); ) {
    names.push(m[1]);
  }
  return [...new Set(names)];
}

async function main() {
  const hasGuidesDir = await fileExists(guidesDir);
  if (!hasGuidesDir) {
    console.warn(
      `[generateStrategyGuidesIndex] Skipping: directory not found: ${guidesDir}`,
    );
    return;
  }

  const entries = await fs.readdir(guidesDir, { withFileTypes: true });

  const guideFiles = entries
    .filter((e) => e.isFile())
    .map((e) => e.name)
    .filter(
      (name) =>
        /\.(ts|tsx)$/.test(name) &&
        !name.endsWith(".d.ts") &&
        name !== "index.ts" &&
        name !== "index.tsx",
    )
    .sort((a, b) => a.localeCompare(b));

  const imports = [];
  const exportedNames = [];

  for (const filename of guideFiles) {
    const abs = path.join(guidesDir, filename);
    const source = await fs.readFile(abs, "utf8");
    const names = extractExportNames(source);

    if (!names.length) {
      console.warn(
        `[generateStrategyGuidesIndex] No 'export const ... =' found in ${filename}; skipping`,
      );
      continue;
    }

    const modulePath = `./${path.basename(filename).replace(/\.(ts|tsx)$/, "")}`;
    imports.push(
      `import { ${names.join(", ")} } from "${toPosixPath(modulePath)}";`,
    );
    exportedNames.push(...names);
  }

  const uniqueNames = [...new Set(exportedNames)];

  const banner =
    "// This file is auto-generated by scripts/generateStrategyGuidesIndex.mjs\n" +
    "// Do not edit by hand.\n";

  const body = [
    banner,
    ...imports,
    "",
    `export const strategyGuides = [${uniqueNames.join(", ")}] as const;`,
    "export type StrategyGuide = (typeof strategyGuides)[number];",
    "",
  ].join("\n");

  await fs.writeFile(outFile, body, "utf8");

  const relOut = path.relative(repoRoot, outFile);
  console.log(
    `[generateStrategyGuidesIndex] Wrote ${relOut} with ${uniqueNames.length} guide export(s)`,
  );
}

await main();
