// This file is auto-generated by scripts/generateStrategyGuidesIndex.mjs
// Do not edit by hand.

import { commonKnowledge } from "./commonKnowledge";
import { jeopardy } from "./jeopardy";
import { dealOrNoDeal } from "./dealOrNoDeal";

export const strategyGuides = [
  jeopardy,
  dealOrNoDeal,
  commonKnowledge,
] as const;
export type StrategyGuide = (typeof strategyGuides)[number];
